export default
{
    "id": "HOMES-3201",
    "url": "/test-stub-gallery-3201",
    "path": ["HOMES--1", "HOMES-1158", "HOMES-1579", "HOMES-2783", "HOMES-3196", "HOMES-3201"],
    "tags": ["food:Location and setting:Australia:Victoria:Mornington Peninsula", "food:Homes navigation:Home Tours", "food:Topic:Luxury home", "food:Decorating:Style:Coastal/beach"],
    "level": 5,
    "nodeId": "HOMES-3201",
    "source": "Australian House and Garden",
    "siteUrl": "http://dev.homes-site.bauer-media.net.au",
    "urlName": "test-stub-gallery",
    "nodeName": "Test stub gallery",
    "parentID": "HOMES-3196",
    "siteCode": "56421E16-B4AB-417C-9645-A6A89644D4B4",
    "siteName": "homes",
    "pageTitle": "A Bushland Retreat On The Mornington Penisular",
    "sortOrder": 3,
    "contentBody": [{
        "type": "paragraph",
        "label": "Paragraph",
        "content": "The breathtaking natural surrounds of the Mornington Peninsula is what made this location supremely appealing to interior designer, Ljiljana Gazevic and her architect partner, Axel Baumann, when they were looking for a property to renovate. Their objective was to create a home with longevity and simplicity – for them the very essence of luxury. \n\n‘Quiet, calming and restorative’ were key words that directed the renovation, creating a home that is “serene and tranquil, allowing us to revive and recharge”, says Ljiljana. These qualities were approached spatially, through the modulation of light and shadow, and through furnishings and finishes. \n\nA new [pavilion-style](http://www.homestolove.com.au/gallery-level-best-2638|target=\"_blank\") extension alongside a reworking of the old floorplan has created a contemporary home. Ceiling heights were raised to allow the insertion of larger windows to maximise natural light, softening the interior and connecting with the landscape. \n\nSimplicity is the hallmark of the interior as well, integrating Japanese influences and Nordic design sensibilities. A minimalist aesthetic is created through a limited palette of materials, taking inspiration from the landscape. Muted tones of grey, white and black, combined with warm and textured limed oak timber, reflect the natural beauty outside, linking interior with exterior.\n \nIn this home away from home, recharging is the necessity. And in this state of relaxation, inspiration comes easily, helped along by the carefully curated art, furniture and object collection that is always evolving.\n\n*Belle*\nPhotos: Nicole England\nStory: Nicky Lobo"
    }],
    "contentTags": ["food:Location and setting:Australia:Victoria:Mornington Peninsula", "food:Homes navigation:Home Tours", "food:Topic:Luxury home", "food:Decorating:Style:Coastal/beach"],
    "contentYear": 2016,
    "navIsHidden": 0,
    "navRedirect": {"Url": null, "Mode": 2, "Title": "", "NodeId": null, "NewWindow": false},
    "tagsDetails": [{
        "name": "food:Topic:Luxury home",
        "urlName": "luxury-home",
        "fullName": "food_Topic_Luxury_home",
        "displayName": "Luxury home"
    }, {
        "name": "food:Decorating:Style:Coastal/beach",
        "urlName": "coastal-beach",
        "fullName": "food_Decorating_Style_Coastalbeach",
        "displayName": "Coastal/beach"
    }, {
        "name": "food:Homes navigation:Home Tours",
        "urlName": "home-tours",
        "fullName": "food_Homes_navigation_Home_Tours",
        "displayName": "Home Tours"
    }, {
        "name": "food:Location and setting:Australia:Victoria:Mornington Peninsula",
        "urlName": "mornington-peninsula",
        "fullName": "food_Location_and_setting_Australia_Victoria_Mornington_Peninsula",
        "displayName": "Mornington Peninsula"
    }],
    "contentMonth": 11,
    "contentTitle": "A luxurious bushland retreat",
    "contentVideo": "",
    "contentAuthor": ["HOMES-2040"],
    "nodeTypeAlias": "Gallery",
    "contentAuthors": ["HOMES-2040"],
    "contentGallery": [{
        "url": "http://dev.assets.cougar.bauer-media.net.au/s3/digital-cougar-assets-dev/homes/2016/11/23/1479870081240_1479341507654WhiteHouseSJB.jpg",
        "open": false,
        "tags": [],
        "title": "Mornington Peninsular Home.jpg",
        "valid": true,
        "source": "",
        "caption": "The pavilion-style renovation features a slatted screen with a minimalist Japanese ethos, echoed in the pebble and rock filled garden which offers a tranquil contemplation space. The large timber platform provides a welcoming entry and outdoor entertaining area.",
        "credits": [],
        "mediaType": "image"
    }, {
        "url": "http://dev.assets.cougar.bauer-media.net.au/s3/digital-cougar-assets-dev/homes/2016/11/23/1479870132577_1479336337608SJB-WhiteHouse12.jpg",
        "open": false,
        "tags": [],
        "title": "SJB - White House (12).jpg",
        "valid": true,
        "source": "",
        "caption": "Painting by Matthew Johnson. Zanotta ‘Edizioni Zeus’ table and Vitra ‘Cork’ stool, both from [Space](http://www.spacefurniture.com.au/|target=\"_blank\"|rel=\"nofollow\").",
        "credits": [],
        "mediaType": "image"
    }, {
        "open": false,
        "valid": true,
        "ispoen": false,
        "videoId": "3976804555001",
        "mediaType": "video",
        "videoTitle": "",
        "brightcoveId": "3976804555001"
    }, {
        "url": "http://dev.assets.cougar.bauer-media.net.au/s3/digital-cougar-assets-dev/homes/2016/11/23/1479870207717_1479336331300SJB-WhiteHouse3.jpg",
        "open": false,
        "tags": [],
        "title": "SJB - White House (3).jpg",
        "valid": true,
        "source": "",
        "caption": "Textured stone platforms in the living room, reminiscent of volcanic stone found on nearby beaches, act as informal seating. Limited-edition woven dining chairs, prismatic cubed side tables and the ‘Smock’ armchair by [Patricia Urquiola](http://www.patriciaurquiola.com/|target=\"_blank\"|rel=\"nofollow\"). Textured handwoven rugs, found on holiday in Tropea, Calabria, inject just the right amount of colour and pattern.",
        "credits": [],
        "mediaType": "image"
    }, {
        "url": "http://dev.assets.cougar.bauer-media.net.au/s3/digital-cougar-assets-dev/homes/2016/11/23/1479870235980_1479336326377SJB-WhiteHouse8.jpg",
        "open": false,
        "tags": [],
        "title": "SJB - White House (8).jpg",
        "valid": true,
        "source": "",
        "caption": "Sunburnt Country sculpture by Piers Buxton, is displayed on the fireplace’s floating stone platform.",
        "credits": [],
        "mediaType": "image"
    }, {
        "url": "http://dev.assets.cougar.bauer-media.net.au/s3/digital-cougar-assets-dev/homes/2016/11/23/1479870264253_1479336345745SJB-WhiteHouse11.jpg",
        "open": false,
        "tags": [],
        "title": "SJB - White House (11).jpg",
        "valid": true,
        "source": "",
        "caption": "The pendant lights above the dining table are a custom design by [Anchor Ceramics](http://anchorceramics.com/|target=\"_blank\"|rel=\"nofollow\"). The overscale barn door was designed by Ljiljana and separates the guest quarters from the dining and entry.",
        "credits": [],
        "mediaType": "image"
    }, {
        "url": "http://dev.assets.cougar.bauer-media.net.au/s3/digital-cougar-assets-dev/homes/2016/11/23/1479870302994_1479336358195SJB-WhiteHouse16.jpg",
        "open": false,
        "tags": [],
        "title": "SJB - White House (16).jpg",
        "valid": true,
        "source": "",
        "caption": "Exfoliated granite benchtop and timber veneer cupboards in the kitchen create a naturally sleek profile. The ‘Vela’ outdoor chairs are from [Space](http://www.spacefurniture.com.au/|target=\"_blank\"|rel=\"nofollow\").",
        "credits": [],
        "mediaType": "image"
    }, {
        "url": "http://dev.assets.cougar.bauer-media.net.au/s3/digital-cougar-assets-dev/homes/2016/11/23/1479870372263_1479336362494SJB-WhiteHouse20.jpg",
        "open": false,
        "tags": [],
        "title": "SJB - White House (20).jpg",
        "valid": true,
        "source": "",
        "caption": "The bespoke wardrobe was custom designed by Ljiljana. The Belgian linen duvet and knitted leather throw add a soft touch, while the handwoven rug bought in Calabria, injects colour.",
        "credits": [],
        "mediaType": "image"
    }],
    "contentSummary": "A quiet place on the Mornington Peninsula to relax and recharge has also become a source of inspiration for these creative owners.",
    "moduleParentId": "HOMES-3201",
    "pageSearchTags": ["Mornington Peninsula", "Mornington-Peninsula", "mornington-peninsula", "mornington peninsula", "Home Tours", "Home-Tours", "home-tours", "home tours", "Luxury home", "Luxury-home", "luxury-home", "luxury home", "Coastal/beach", "coastal/beach"],
    "contentCampaign": [],
    "contentHasVideo": false,
    "contentImageUrl": "http://dev.assets.cougar.bauer-media.net.au/s3/digital-cougar-assets-dev/homes/2016/11/23/3201/1479341507654_WhiteHouseSJB.jpg",
    "contentProfiles": [{
        "id": "HOMES-2040",
        "url": "/contributors/nicole-england",
        "name": "Nicole England",
        "level": 3,
        "pathIds": ["HOMES--1", "HOMES-1158", "HOMES-1314", "HOMES-2040"],
        "siteUrl": "http://dev.homes-site.bauer-media.net.au",
        "urlName": "nicole-england",
        "nodeType": "HomesProfile",
        "parentId": "HOMES-1314",
        "redirect": {"mode": 2},
        "siteCode": "56421E16-B4AB-417C-9645-A6A89644D4B4",
        "siteName": "homes",
        "typeName": "HomesProfileTeaserDto",
        "sortOrder": 203,
        "dateIndexed": "2016-11-21T11:25:45",
        "profileType": "photographer",
        "nodeTypeAliasPath": ["Page", "Profiles", "HomesProfile"]
    }],
    "nodeDateIndexed": "2016-11-23T03:09:40.86Z",
    "pageDateCreated": "2016-11-23T03:00:27.00Z",
    "nodeTypeAliasPath": ["Page", "Editorial", "Gallery"],
    "contentPhotoCredit": "Nicole England",
    "contentAccessLevels": -1,
    "contentImageAltText": "Mornington Peninsular home",
    "contentSummaryTitle": "A luxurious bushland retreat",
    "pageMetaDescription": "A quiet place on the Mornington Peninsula to relax and recharge was the main a source of inspiration for these owners when designing their own home.",
    "pageExcludeFromSitemap": 0,
    "contentFacebookImageUrl": {"tags": [], "source": "", "credits": []},
    "pageExcludeDescendantsFromSitemap": 0,
    "updated_at": "2016-11-23T03:09:41.318Z"
}

