# This jobs are only used for HOMESTOLOVE

####################################################################
# Refer to http://docs.shippable.com/reference/jobs-overview/      #
# Resources are located in shippable.resources.yml file            #
# Jobs are numbered to visualize sequence                          #
####################################################################

jobs:

  # 1. Sync pipeline to CI
  - name: homes-site_runCI
    type: runCI
    steps:
      - OUT: homes-site-img-master
      - OUT: homes-site-img-branch

  # 2branch. Manifest for a BRANCH image
  - name: homes-site-man-branch
    type: manifest
    steps:
      - IN: homes-site-img-branch
      - IN: homes-site-opts-sit
      - TASK: managed
    flags:
      - homes-site

  # 3Branch. SIT deployment for feature BRANCH
  - name: homes-site-sit-deploy-branch
    type: deploy
    always:
      - NOTIFY: homes-slack-notifications
    steps:
      - IN: homes-site-replicas-non-prod #number of running tasks
      - IN: homes-site-man-branch # for non-master, don't auto deploy.
        switch: off
      - IN: homes-env-sit-ecs
      - IN: homes-site-params-sit
      - IN: homes-site-alb-sit-branch
        applyTo:
          - manifest: homes-site-man-branch
            image: homes-site-img-branch
            port: 3001
      - TASK: managed
        deployMethod: replace

  # 2. Manifest for MASTER image
  - name: homes-site-man-master
    type: manifest
    steps:
      - IN: homes-site-img-master
      - IN: homes-site-opts-sit
      - TASK: managed

  # 3a. SIT deployment for MASTER
  - name: homes-site-sit-deploy-master
    type: deploy
    always:
      - NOTIFY: homes-slack-notifications
    steps:
      - IN: homes-site-replicas-non-prod #number of running tasks
      - IN: homes-site-man-master # for master - auto deploy to SIT
        switch: on
      - IN: homes-env-sit-ecs
      - IN: homes-site-params-sit
      - IN: homes-site-alb-sit
        applyTo:
          - manifest: homes-site-man-master
            image: homes-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: replace

  # 3b. TEST deployment for MASTER - stubbed
  - name: homes-site-test-deploy-master
    type: deploy
    steps:
      - IN: homes-site-replicas-non-prod #number of running tasks
      - IN: homes-site-man-master # for master - auto deploy to SIT
        switch: on
      - IN: homes-env-sit-ecs
      - IN: homes-site-params-test
      - IN: homes-site-alb-test
        applyTo:
          - manifest: homes-site-man-master
            image: homes-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: replace

  # 4a. Run regression test on TEST environment
  - name: homes-site-automation-test
    type: runSh
    always:
      - NOTIFY: homes-slack-notifications
    steps:
     - IN: homes-site-test-deploy-master
     - IN: homes-site-repo
       switch: off
     - TASK:
        - script: until(curl --fail homes.test.bxm.net.au/version); do echo "Pinging Homes Version Page..."; sleep 5; done
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/homes-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://homes.test.bxm.net.au/
        - script: npm run test:high || true
        - script: actualsize=$(wc -c <"@rerun.txt")
        - script: bash -c "if [ $actualsize -eq 0 ]; then  echo 'rerun exit code' $actualsize; else npm run test:rerun; fi"

  # 4b. Run mobile regression test on TEST environment - Browser Stack
  - name: homes-site-mobile-automation-test
    type: runSh
    always:
      - NOTIFY: homes-slack-notifications
    steps:
     - IN: homes-site-test-deploy-master
     - IN: homes-site-repo
       switch: off
     - TASK:
        - script: until(curl --fail homes.test.bxm.net.au/version); do echo "Pinging Homes Version Page..."; sleep 5; done     
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/homes-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: rm -rf node_modules/chimp/dist/lib/cucumberjs/hooks.js
        - script: cp features/support/files/chimp_hooks.backup node_modules/chimp/dist/lib/cucumberjs/hooks.js
        - script: export URL=http://homes.test.bxm.net.au/
        - script: npm run test:mobile

  # 5. Package release for production release
  - name: homes-site-release-master
    type: release
    steps:
      - IN: homes-site-automation-test
      - IN: homes-site-man-master
        switch: off
      - IN: homes-site-version
      - TASK: managed
        bump: minor

  # 6. PROD deployment for MASTER with Region AU
  - name: homes-site-prod-deploy-master
    type: deploy
    always:
      - NOTIFY: homes-slack-notifications
    steps:
      - IN: homes-site-replicas-production #number of running tasks
      - IN: homes-site-release-master
        switch: off
      - IN: env-prod-ecs
      - IN: homes-site-params-prod
      - IN: homes-site-alb-prod
        applyTo:
          - manifest: homes-site-man-master
            image: homes-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: upgrade
