# This jobs are only used for HOMESTOLOVE

####################################################################
# Refer to http://docs.shippable.com/reference/jobs-overview/      #
# Resources are located in shippable.resources.yml file            #
# Jobs are numbered to visualize sequence                          #
####################################################################

jobs:

  # 1. Sync pipeline to CI
  - name: homes-site_runCI
    type: runCI
    steps:
      - OUT: homes-site-img-master
      - OUT: homes-site-img-branch

  # 2branch. Manifest for a BRANCH image
  - name: homes-site-man-branch
    type: manifest
    steps:
      - IN: homes-site-img-branch
      - IN: homes-site-opts-sit
      - TASK: managed

  # 3Branch. SIT deployment for feature BRANCH
  - name: homes-site-sit-deploy-branch
    type: deploy
    always:
      - NOTIFY: homes-slack-notifications
    steps:
      - IN: homes-site-replicas-non-prod #number of running tasks
      - IN: homes-site-man-branch # for non-master, don't auto deploy.
        switch: off
      - IN: homes-env-sit-ecs
      - IN: homes-site-params-sit
      - IN: homes-site-alb-sit-branch
        applyTo:
          - manifest: homes-site-man-branch
            image: homes-site-img-branch
            port: 3001
      - TASK: managed
        deployMethod: replace

  # 2. Manifest for MASTER image
  - name: homes-site-man-master
    type: manifest
    steps:
      - IN: homes-site-img-master
      - IN: homes-site-opts-sit
      - TASK: managed

  # 3a. SIT deployment for MASTER
  - name: homes-site-sit-deploy-master
    type: deploy
    always:
      - NOTIFY: homes-slack-notifications
    steps:
      - IN: homes-site-replicas-non-prod #number of running tasks
      - IN: homes-site-man-master # for master - auto deploy to SIT
        switch: on
      - IN: homes-env-sit-ecs
      - IN: homes-site-params-sit
      - IN: homes-site-alb-sit
        applyTo:
          - manifest: homes-site-man-master
            image: homes-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: replace

  # 3b. TEST deployment for MASTER - stubbed
  - name: homes-site-test-deploy-master
    type: deploy
    always:
      - NOTIFY: homes-slack-notifications
    steps:
      - IN: homes-site-replicas-non-prod #number of running tasks
      - IN: homes-site-man-master # for master - auto deploy to SIT
        switch: on
      - IN: homes-env-sit-ecs
      - IN: homes-site-params-test
      - IN: homes-site-alb-test
        applyTo:
          - manifest: homes-site-man-master
            image: homes-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: replace

  # 4a. Run regression test on TEST environment
  - name: homes-site-automation-test
    type: runSh
    runtime:
      nodePool: custom__x86_64__Ubuntu_16_04
    always:
      - NOTIFY: homes-slack-notifications
      - NOTIFY: homes-qa-team-notifications
    steps:
     - IN: homes-site-test-deploy-master
     - IN: homes-site-repo
       switch: off
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "8.9.1"
        - script: nvm use "8.9.1"
        - script: cd ./IN/homes-site-repo/gitRepo/automation
        - script: npm set @bxm:registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://homes-site.test.bxm.net.au/
        - script: npm run test:high || true
        - script: actualsize=$(wc -c <"@rerun.txt")
        - script: bash -c "if [ $actualsize -eq 0 ]; then  echo 'rerun exit code' $actualsize; else npm run test:rerun; fi"
    on_failure:
      - NOTIFY: homes-deployment-notifications

  # 4b. Run compatibility regression test on TEST environment - Browser Stack
  - name: homes-site-compatibility-automation-test
    type: runSh
    runtime:
     nodePool: custom__x86_64__Ubuntu_16_04
    always:
      - NOTIFY: homes-slack-notifications
      - NOTIFY: homes-qa-team-notifications
    steps:
     - IN: homes-site-test-deploy-master
     - IN: homes-site-repo
       switch: off
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "8.9.1"
        - script: nvm use "8.9.1"
        - script: cd ./IN/homes-site-repo/gitRepo/automation
        - script: npm set @bxm:registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: rm -rf node_modules/chimp/dist/lib/cucumberjs/hooks.js
        - script: cp features/support/files/chimp_hooks.backup node_modules/chimp/dist/lib/cucumberjs/hooks.js
        - script: export URL=http://homes-site.test.bxm.net.au/
        - script: npm run test:mobile
        - script: npm run test:browser
    on_failure:
      - NOTIFY: homes-deployment-notifications

  # 4c. Smoke test
  - name: homes-site-smoke-test
    type: runSh
    runtime:
     nodePool: custom__x86_64__Ubuntu_16_04
    always:
      - NOTIFY: homes-slack-notifications
      - NOTIFY: homes-qa-team-notifications
    steps:
     - IN: homes-site-sit-deploy-master
     - IN: homes-site-repo
       switch: off
     - TASK:
        - script: curl services.sit.bxm.internal/publishing-broker/
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "8.9.1"
        - script: nvm use "8.9.1"
        - script: cd ./IN/homes-site-repo/gitRepo/automation
        - script: npm set @bxm:registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=https://www.sit.homestolove.com.au/
        - script: APP_KEY=homes-site npm run sit:au || true
        - script: actualsize=$(wc -c <"@rerun.txt")
        - script: bash -c "if [ $actualsize -eq 0 ]; then  echo 'rerun exit code' $actualsize; else npm run test:rerun; fi"
    on_failure:
      - NOTIFY: homes-deployment-notifications

  # 5. Package release for production release
  - name: homes-site-release-master
    type: release
    dependencyMode: strict
    always:
      - NOTIFY: homes-slack-notifications
    steps:
      - IN: homes-site-smoke-test
      - IN: homes-site-automation-test
      - IN: homes-site-man-master
        switch: off
      - IN: homes-site-version
      - TASK: managed
        bump: minor
    on_success:
      - NOTIFY: homes-deployment-notifications

  # 6. PROD deployment for MASTER with Region AU
  - name: homes-site-prod-deploy-master
    type: deploy
    always:
      - NOTIFY: homes-slack-notifications
      - NOTIFY: homes-deployment-notifications
    steps:
      - IN: homes-site-replicas-production #number of running tasks
      - IN: homes-site-release-master
        switch: off
      - IN: homes-env-prod-ecs
      - IN: homes-site-params-prod
      - IN: homes-site-alb-prod
        applyTo:
          - manifest: homes-site-man-master
            image: homes-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: upgrade


  ##############################################
  # Schedule jobs - not attached to the pipeline
  ##############################################


  # i. Full regression in TEST
  - name: FULL-homes-site-regression-test
    type: runSh
    runtime:
     nodePool: custom__x86_64__Ubuntu_16_04
    always:
      - NOTIFY: homes-qa-team-notifications
    steps:
     - IN: homes-site-repo
       switch: off
     - IN: homes-morning-trigger
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "8.9.1"
        - script: nvm use "8.9.1"
        - script: cd ./IN/homes-site-repo/gitRepo/automation
        - script: npm set @bxm:registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://homes-site.test.bxm.net.au/
        - script: export APP_KEY=homes-site
        - script: APP_KEY=homes-site npm run test:phantom || true
        - script: node rerun.combine.js
        - script: actualsize=$(wc -c <"@rerun.txt")
        - script: bash -c "if [ $actualsize -eq 0 ]; then  echo 'rerun exit code' $actualsize; else npm run test:rerun; fi"

  # ii. Smoke Test in Homes Dev CMS
  - name: CMS-homes-smoke-test
    type: runSh
    runtime:
     nodePool: custom__x86_64__Ubuntu_16_04
    always:
      - NOTIFY: homes-qa-team-notifications
    steps:
     - IN: homes-site-repo
       switch: off
     - IN: homes-weekly-trigger
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "8.9.1"
        - script: nvm use "8.9.1"
        - script: cd ./IN/homes-site-repo/gitRepo/automation
        - script: npm set @bxm:registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://cms.dev.homes.wn.bauer-media.net.au/cms/umbraco/
        - script: APP_KEY=homes-site npm run test:cms || true
        - script: actualsize=$(wc -c <"@rerun.txt")
        - script: bash -c "if [ $actualsize -eq 0 ]; then  echo 'rerun exit code' $actualsize; else npm run test:rerun; fi"

  # iii. Run Performance Test on live environment for troubleshooting feature/add-lighthouse-test
  - name: homes-site-performance-test-live-troubleshooting
    type: runSh
    always:
      - NOTIFY: homes-qa-team-notifications
    steps:
     - IN: homes-site-repo-branch
       switch: off
     #- IN: homes-weekly-trigger
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "8.9.1"
        - script: nvm use "8.9.1"
        - script: cd ./IN/homes-site-repo-branch/gitRepo/src
        - script: npm set @bxm:registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        - script: sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        - script: sudo apt-get update
        - script: sudo apt-get install google-chrome-stable
        - script: google-chrome --product-version
        - script: npm run test:perflive