automation:
  web: http://automation.homes.wn.bauer-media.net.au/
  solr: http://solr-cluster01.digital.dev.local/solr/
  solr_collection_name: home-site-automation
  solr_collection_search_name: home-search-automation

local:
  web:http://localhost:80

stubbed:
  web:http://localhost:8080