# config/cucumber.yml
##YAML Template
---
default: --format pretty --format html --out=artifacts/<%= Time.now.strftime("%Y%m%d-%H%M%S") %>-features_report<%= ENV['BS_AUTOMATE_OS_VERSION'] %><%= ENV['SELENIUM_BROWSER'] %><%= ENV['SELENIUM_VERSION'] %>.html
