var homepage_widget = {

    heroImg: '.section-featured--top .teaser--hero',
    heroImgUrl: '.section-featured--top .teaser--hero img',
    heroImgLink: '.section-featured--top .teaser--hero .teaser__image',
    heroCustomLabel: '.hero-wrapper .teaser__badge',
    heroLabelPosition: '.hero-wrapper .teaser__sub-section-container',
    heroTitle: '.section-featured--top .teaser--hero .teaser__title',
    heroTitleLink: '.section-featured--top .teaser--hero .teaser__title>a',
    heroShortTeaser: '.section-featured--top .teaser--hero .teaser__summary',
    heroSource: '.section-featured--top .teaser--hero .teaser__source',
    heroSourceLink: '.section-featured--top .teaser--hero .teaser__source>a',
    heroTag: ".section-featured--top .teaser--hero .teaser__tags [class^='tag-']",
    topTeasers: '.section-featured--top .teaser',
    topTeaserImgs: '.section-featured--top .teaser img',
    topTeaserTitles: '.section-featured--top .teaser__title',
    topTeaserTags: ".section-featured--top .teaser__tags [class^='tag-']",
    topTeaserTagLinks: ".section-featured--top .teaser__tags [class^='tag-'] a",
    heroStyle: '.content-wrapper .stripe-bg',
    trendingTitle: '.trending__caption.hide-for-xlarge-up img',
    bottomFeed: '.teaser__list.teaser-view-list',
    teaserImgUrl: '.teaser__image img',
    topFeedNumber: '.teaser__list.teaser-view-grid article.teaser',
    topFeedImg: '.teaser__list.teaser-view-grid .teaser__image',
    topCustomLabel: '.teaser__list.teaser-view-grid .teaser__badge',
    topFeedLongTitles: '.teaser__list.teaser-view-grid .teaser__title',
    topFeedShortTeasers: '.teaser__list.teaser-view-grid .teaser__summary-wrap',
    topFeedImgUrls: '.teaser__list.teaser-view-grid .teaser__image img',
    topFeedTeaserTitle: '.teaser__list.teaser-view-grid .teaser__title a',
    bottomFeedNumber: '.teaser__list.teaser-view-list article.teaser',
    bottomFeedTeaserImg: '.teaser__list.teaser-view-list .teaser__image ',
    bottomFeedTeaserTitle: '.teaser__list.teaser-view-list .teaser__title a',
    bottomFeedImgUrls: '.teaser__list.teaser-view-list .teaser__image img',
    bottomCustomLabel:'.teaser__list.teaser-view-list .teaser__badge, teaser__sub-section',
    bottomFeedLongTitles: '.teaser__list.teaser-view-list .teaser__title',
    bottomFeedShortTeasers: '.teaser__list.teaser-view-list .teaser__summary-wrap',
    bottomFeedImg: '.teaser__list.teaser-view-list .teaser__image'

};
module.exports = homepage_widget;
